name = "fps3"
compatibility_date = "2026-05-28"
main = "src/worker.ts"


[vars]
TURNSTILE_SITE_KEY = "0x4AAAAAADzFDHXgSOCnjEAB"
TURNSTILE_HOSTNAME = "fps.luigismansion.de"

[assets]
directory = "./dist"

[[durable_objects.bindings]]
name = "TURN_RATE_LIMITER"
class_name = "TurnRateLimiter"

[[durable_objects.bindings]]
name = "ACTIVE_TURN_ROOM"
class_name = "ActiveTurnRoom"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["TurnRateLimiter", "ActiveTurnRoom"]
